### ISSUE TITLE
recieving error if using curlreuqest in a nested calls

### ISSUE THREAD

**Issue by pulkitnandan** [chriso/curlrequest#30]
Why I'm fine with a create crud op when done with a get request from browser or curl desktop client while when I do the same with curlrequest in nodejs app I recieve following error

The server didn't reply anything, which here is considered an error.

**Comment by chriso** [comment]
Can you provide some example code and a stack trace that highlights the problem?

**Comment by pulkitnandan** [comment]
Here goes the stack trace 

child_process.js:1164
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENOMEM
    at exports._errnoException (util.js:748:11)
    at ChildProcess.spawn (child_process.js:1164:11)
    at Object.exports.spawn (child_process.js:997:9)
    at module.exports (/root/backend/node_modules/curlrequest/spawn.js:19:30)
    at Object.exports.request (/root/backend/node_modules/curlrequest/index.js:257:17)
    at insertCandidates (/root/backend/cron/candidates.js:71:30)
    at Object.<anonymous> (/root/backend/cron/candidates.js:97:33)
    at finish (/root/backend/node_modules/curlrequest/index.js:122:18)
    at ChildProcess.<anonymous> (/root/backend/node_modules/curlrequest/index.js:334:13)
    at ChildProcess.emit (events.js:112:17)


And here goes the code

**Comment by chriso** [comment]
Is this running in a loop? `ENOMEM` means you're out of memory and probably trying to spawn too many child processes.

**Comment by pulkitnandan** [comment]
No its running in a recursion, my usecase requires first to use curlrequest fectch a page with 100 items, after fetching it again uses the same curl object to fetch details of those 100 items, which happens in a recursion too.

**Comment by chriso** [comment]
`curl.request()` returns before the request is finished, since spawning child processes is non-blocking. This means that the recursive pattern you're using will fire off all of the curl requests in quick succession and you'll quickly run out of memory or file descriptors, as you're seeing in the error. You'll need to use an asynchronous loop here. I'd recommend using `async.eachLimit` from the [async.js](https://github.com/caolan/async) library.
